import serial

def main():
	serialport = serial.Serial('/dev/serial0', 115200)
	packet = bytearray()
	packet.append(0x7e)
	packet.append(0xbe)
	packet.append(0xda)
	packet.append(0x8d)
	packet.append(0xf2)
	packet.append(0x3b)
	packet.append(0x15)
	packet.append(0x4d)
	packet.append(0x5d)
	packet.append(0x09)
	packet.append(0x5b)
	packet.append(0xf9)
	packet.append(0xd0)
	packet.append(0x31)
	packet.append(0x95)
	packet.append(0x0f)
	packet.append(0x77)
	packet.append(0x8e)
	packet.append(0x51)
	packet.append(0x79)
	packet.append(0x7e)
	serialport.write(packet)

if __name__ == '__main__':
	main()
