#!/bin/bash
#TXISR CONFIG Reenable

filename="/boot/config.txt"

# if enable_uart is found in the file, set it to 0. if it is not, append enable_uart=1. Use ternary operator
grep -q 'enable_uart.*=' ${filename} && sed -i 's/^enable_uart.*=.*/enable_uart=1/' ${filename} || echo 'enable_uart=1' >> ${filename}
systemctl restart serial-getty@ttyAMA0.service
